# Generated by Django 3.1.1 on 2020-10-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=300)),
                ('city_details', models.CharField(max_length=10000)),
                ('airport_details', models.CharField(max_length=2000)),
                ('railway_station_details', models.CharField(max_length=2000)),
                ('bus_stand_details', models.CharField(max_length=2000)),
            ],
        ),
    ]
