# Generated by Django 3.1.1 on 2020-11-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20201025_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=30)),
                ('contact', models.CharField(default='', max_length=13)),
                ('description', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=15)),
                ('location', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
