# Generated by Django 3.1.1 on 2020-11-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
