# Generated by Django 3.1.4 on 2021-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_explorecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.ImageField(default='', upload_to='City/images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_cities',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
